const courses = [
  'web-standards-1', 
  'animation-1',
  'web-graphics-1',
]

const students = [
    {
      id: 1,
      avatar: '/images/studenten/anniek-de-water.jpg',
      name: 'Anniek De Water',
      group: 'a',
      courses: [courses[0], courses[1]],
      firstName: 'Anniek',
      lastName: 'De Water',
      gender: 'f',
    },
    {
      id: 2,
      avatar: '/images/studenten/dillan-morel.jpg',
      name: 'Dillan Morel',
      group: 'b',
      courses: [courses[2]],
      firstName: 'Dillan',
      lastName: 'Morel',
      gender: 'm',
    },
    {
      id: 3,
      avatar: '/images/studenten/flynn-van-niel.jpg',
      name: 'Flynn Van Niel',
      group: 'b',
      courses: [courses[0], courses[2]],
      firstName: 'Flynn',
      lastName: 'Van Niel',
      gender: 'm',
    },
    {
      id: 4,
      avatar: '/images/studenten/hans-de-langen.jpg',
      name: 'Hans De Langen',
      group: 'a',
      courses: [courses[0], courses[1]],
      firstName: 'Hans',
      lastName: 'De Langen',
      gender: 'm',
    },
    {
      id: 5,
      avatar: '/images/studenten/indigo-van-denderen.jpg',
      name: 'Indigo Van Denderen',
      group: 'b',
      courses: [courses[0], courses[1], courses[2]],      
      firstName: 'Indigo',
      lastName: 'Van Denderen',
      gender: 'm',
    },
    {
      id: 6,
      avatar: '/images/studenten/jense-wallenburg.jpg',
      name: 'Jense Wallenburg',
      group: 'a',
      courses: [courses[0], courses[1]],    
      firstName: 'Jense',
      lastName: 'Wallenburg',  
      gender: 'm',
    },
    {
      id: 7,
      avatar: '/images/studenten/lander-kloosterman.jpg',
      name: 'Lander Kloosterman',
      group: 'c',
      courses: [courses[0], courses[1], courses[2]],   
      firstName: 'Lander',
      lastName: 'Kloosterman',   
      gender: 'm',
    },
    {
      id: 8,
      avatar: '/images/studenten/lander-ten-hoven.jpg',
      name: 'Lander Ten Hoven',
      group: 'b',
      courses: [courses[0], courses[1]],   
      firstName: 'Lander',
      lastName: 'Ten Hoven',   
      gender: 'm',
    },
    {
      id: 9,
      avatar: '/images/studenten/marlene-van-de-laak.jpg',
      name: 'Marlene van de Laak',
      group: 'c',
      courses: [courses[0], courses[2]],   
      firstName: 'Marlene',
      lastName: 'van de Laak',   
      gender: 'f',
    },
    {
      id: 10,
      avatar: '/images/studenten/mattijs-palmen.jpg',
      name: 'Mattijs Palmen',
      group: 'a',
      courses: [courses[0], courses[1], courses[2]],      
      firstName: 'Mattijs',
      lastName: 'Palmen',
      gender: 'm',
    },
    {
      id: 11,
      avatar: '/images/studenten/matijs-van-peer.jpg',
      name: 'Mattijs Van Peer',
      group: 'b',
      courses: [courses[1], courses[2]],  
      firstName: 'Mattijs',
      lastName: 'Van Peer',  
      gender: 'm',  
    },
    {
      id: 12,
      avatar: '/images/studenten/nicolle-clements.jpg',
      name: 'Nicole Clements',
      group: 'b',
      courses: [courses[2]],      
      firstName: 'Nicole',
      lastName: 'Clements',
      gender: 'f',
    },
    {
      id: 13,
      avatar: '/images/studenten/roan-van-ingen.jpg',
      name: 'Roan van Ingen',
      group: 'c',
      courses: [courses[1]],   
      firstName: 'Roan',
      lastName: 'Van Ingen',   
      gender: 'm',
    },
    {
      id: 14,
      avatar: '/images/studenten/saima-kaffa.jpg',
      name: 'Saima Kaffa',
      group: 'c',
      courses: [courses[0], courses[1]],  
      firstName: 'Saima',
      lastName: 'Kaffa',    
    },
    {
      id: 15,
      avatar: '/images/studenten/senne-van-den-bogaart.jpg',
      name: 'Senne van den Bogaart',
      group: 'a',
      courses: [courses[0], courses[1], courses[2]],   
      firstName: 'Senne',
      lastName: 'van den Bogaart',   
      gender: 'm',
    },
    {
      id: 16,
      avatar: '/images/studenten/senne-van-loo.jpg',
      name: 'Senne Van Loo',
      group: 'c',
      courses: [courses[1], courses[2]],   
      firstName: 'Senne',
      lastName: 'Van Loo',  
      gender: 'm', 
    },
    {
      id: 17,
      avatar: '/images/studenten/timmo-duiker.jpg',
      name: 'Timmo Duiker',
      group: 'c',
      courses: [courses[0], courses[2]],   
      firstName: 'Timmo',
      lastName: 'Duiker',
      gender: 'm',   
    },
  ];

module.exports = students;